### ISSUE TITLE
java heap space exception

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfbox#1]
```
INFO  2015-10-01 16:02:53,329 edeposit.amqp.pdfbox.handlers: new message arrived
DefaultExceptionHandler: Consumer langohr.consumers.proxy$com.rabbitmq.client.DefaultConsumer$ff19274a@4d4afa76 (amq.ctag-5Mlg9CP8o0hSW5ABR_-Clw) method handleDelivery for channel AMQChannel(amqp://guest@127.0.0.1:5672pdfbox,1) threw an exception for channel AMQChannel(amqp://guest@127.0.0.1:5672pdfbox,1):
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2367)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587)
        at java.lang.StringBuilder.append(StringBuilder.java:214)
        at clojure.data.json$read_quoted_string.invoke(json.clj:145)
        at clojure.data.json$_read.invoke(json.clj:195)
        at clojure.data.json$read_object.invoke(json.clj:93)
        at clojure.data.json$_read.invoke(json.clj:220)
        at clojure.data.json$read.doInvoke(json.clj:272)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.data.json$read_str.doInvoke(json.clj:278)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at edeposit.amqp.pdfbox.handlers$parse_and_validate.invoke(handlers.clj:47)
        at edeposit.amqp.pdfbox.handlers$handle_delivery.doInvoke(handlers.clj:85)
        at clojure.lang.RestFn.invoke(RestFn.java:529)
        at edeposit.amqp.pdfbox.components.PDFBox-AMQP$handler__2243.invoke(components.clj:21)
        at langohr.consumers$create_default$fn__1415.invoke(consumers.clj:60)
        at langohr.consumers.proxy$com.rabbitmq.client.DefaultConsumer$ff19274a.handleDelivery(Unknown Source)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:95)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

(blocks edeposit/edeposit#627)

**Comment by jstavel** [comment]
do project.clj doplnit :jvm-opts ["-Xmx1G"]

**Comment by jstavel** [comment]
tak toto nepomohlo. Zkusim to jeste zvetsit.

**Comment by jstavel** [comment]
zkousim tento argument primo v project.clj pro balicek edeposit.amqp.pdfbox
